### ISSUE TITLE
A new CV can't be shown on the home page 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#11]
**Added CV**
![image](https://user-images.githubusercontent.com/42932849/71162450-8a83b380-224b-11ea-9e94-91fb3a94581b.png)

**Home Page**
![image](https://user-images.githubusercontent.com/42932849/71162478-95d6df00-224b-11ea-9462-47dc2cec4d59.png)

**Comment by khalid-elabbadi** [comment]
c ton cvtheque ????!!! ça s'affiche pas sur home page ça reste privée pour toi
seul les cvs des candidats sont affichés si ils sont publiés

**Comment by Laila-BENGHABRIT** [comment]
yes got it!
