### ISSUE TITLE
Things to change

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#13]
![image](https://user-images.githubusercontent.com/42932849/71164180-cff5b000-224e-11ea-9006-2d8fe324700c.png)

**Paramètres
Heure système n'est pas correcte
Personnelles** 

![image](https://user-images.githubusercontent.com/42932849/71164344-2531c180-224f-11ea-938c-6c99ee84110a.png)

**Date de naissance n'est pas bien récupérée ainsi que le type de sexe** 

I think that adding Birthday, Sexe should be in the first section "Personnelles"  and "Facultatives" you can add his situation "Married", "Single", "Divorced" also his /her Hobbie , Type de Permis ...

**Comment by khalid-elabbadi** [comment]
Date de naissance n'est pas bien récupérée ainsi que le type de sexe:
ces info sont mise par défaut => noway to get them from linkedin or google (not authorized)

for heure systeme => it is the server hour i will see if there is a way to play that back

**Comment by Laila-BENGHABRIT** [comment]
Ok got you!
