### ISSUE TITLE
Boite de réception not Boite d'envoie 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#16]
![image](https://user-images.githubusercontent.com/42932849/71169371-10f2c200-2259-11ea-881a-231e21a8d4fe.png)

**Comment by khalid-elabbadi** [comment]
no it is boite d'envoi. it contains emails you sent before

**Comment by Laila-BENGHABRIT** [comment]
Ok got you
