### ISSUE TITLE
Please let the candidat change his email 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#17]
![image](https://user-images.githubusercontent.com/42932849/71169508-5fa05c00-2259-11ea-83e5-87d351864829.png)

**Comment by khalid-elabbadi** [comment]
No, email never change because it is the account
no email no account
change email means change account

**Comment by Laila-BENGHABRIT** [comment]
May be the candidat change his email from perso to Professional ! u're identifying him by an ID i guess!

**Comment by khalid-elabbadi** [comment]
no existing system does allow changing emails: facebook google linkedin
simply because the email is the caccount and the email was confirmed so if he changes his email we need to verify it again

**Comment by Laila-BENGHABRIT** [comment]
Ok, if you said so :)
