### ISSUE TITLE
New feature to add in the IHM of "Lot"

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#27]
![image](https://user-images.githubusercontent.com/42932849/72149468-81e25100-33a3-11ea-9c60-ea7d278dd9c9.png)

When selecting the statuts "En entretien" , you may generate a small window where the manager can put the date of the meeting of his or their candidats, so it will be helpfull to make sure a great monitoring of his LOT

**Comment by khalid-elabbadi** [comment]
Seems you did not understand how it works
All needee informations can be specified inside the lot

**Comment by Laila-BENGHABRIT** [comment]
got you
