### ISSUE TITLE
You can also add some textes bellow 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#5]
![image](https://user-images.githubusercontent.com/42932849/71073170-23e59380-2180-11ea-89a1-c4d0217866e0.png)

Ajoutez vos compétences depuis les technologies disponibles pour augmenter vos chances

**Comment by Laila-BENGHABRIT** [comment]
Can't find where shall i edit TAGS!

**Comment by khalid-elabbadi** [comment]
Delete it and add a new one
No edit => i this cases we do not edit we just add and remove
we call them chips

**Comment by Laila-BENGHABRIT** [comment]
Ok, got you (y)
