### ISSUE TITLE
adding date filter for the jobs?

### ISSUE THREAD

**Issue by h4ytam** [khalid-elabbadi/upforjob#59]
it will be great idea if the user can filter with date posted,that way it's gonna be easier to distinguish old from new jobs.

**Comment by khalid-elabbadi** [comment]
Thanks a lot for this great idea. We will add it to backlog

**Comment by khalid-elabbadi** [comment]
I have just had a word with the team about your suggestion and the result is the offers(jobs) are by default sorted from recent to old look here :
![image](https://user-images.githubusercontent.com/31181469/94196967-0252ce80-fead-11ea-8e99-6ae33ab34e9c.png)


Please let me know if you still think that adding sort option is usefull ?

**Comment by h4ytam** [comment]
yeah I see it there but for a better User experience I think  it's better if the date was filter cuz some people don't wanna waste there time going all over the posts and check each date and make sure it's the newest from the oldest ones, as an example indeed use a feature where they show you the newest posts only and you can unmark that if you wanna see all the posts thanks in advance.

**Comment by khalid-elabbadi** [comment]
OK. We will do something about it
It will be back to backlog
Thanks a lot

**Comment by khalid-elabbadi** [comment]
This feature was delivered 5 minutes ago as adding a flag new indicating offers added during the current week
![image](https://user-images.githubusercontent.com/31181469/94268859-aed89300-ff35-11ea-9989-64988ed3de37.png)

Please close this issue if satisfied

Thanks
