### ISSUE TITLE
You can add a check list while posting a new offer job to check if it's for Freelance, CDI, CDD, others..

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#7]
**It will facilate also the search option by "recruteurs" =====> it means you can add a filter in your search option**

![image](https://user-images.githubusercontent.com/42932849/71073994-c18d9280-2181-11ea-8084-dbb9ed1a7918.png)

**Comment by khalid-elabbadi** [comment]
i do not think so
you need to mention this inside the offer texte

**Comment by Laila-BENGHABRIT** [comment]
But i think it's quicker than write it, however, you are the conceptor :) 

Will close it
