### ISSUE TITLE
BUG in search option 

### ISSUE THREAD

**Issue by Laila-BENGHABRIT** [khalid-elabbadi/upforjob#9]
i added a new profil whos name is fatima, 
*1: it doesn't appear in the home 
*2: while searching for her, i got this bug 

![image](https://user-images.githubusercontent.com/42932849/71074825-4200c300-2183-11ea-9f07-a26ee5e8ae1f.png)

**Comment by Laila-BENGHABRIT** [comment]
i can find all CVs, but no Fatima, 
may be i still not get the mecanisme of adding CV, please explain the procedure! 
![image](https://user-images.githubusercontent.com/42932849/71356265-efa81380-2581-11ea-84f5-b5fc78f33848.png)

**Comment by khalid-elabbadi** [comment]
searching is working
![image](https://user-images.githubusercontent.com/31181469/71408962-38260680-2640-11ea-86be-dd9417bd7a1c.png)

**Comment by khalid-elabbadi** [comment]
if she blocks you you would not find her

**Comment by Laila-BENGHABRIT** [comment]
I added the profil, how can i know that she blocked me??
